"""
Django settings for bluepages project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "FIX_THIS_FOR_PRODUCTION"

DEBUG = False
DEBUG_JS = DEBUG

ALLOWED_HOSTS = [
    "*",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sitemaps",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "address",
    "app",
    "phone_field",
    "reversion",
    "sass_processor",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "bluepages.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "bluepages/templates"),
            os.path.join(BASE_DIR, "app/templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.media",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bluepages.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "bluepages",
        "USER": "postgres",
        # 'PASSWORD': '',
        # 'HOST': 'localhost',
        # 'PORT': 5432,
    }
}

# LOGGING
# Set logging to default, and then make admin error emails come through as HTML
from django.utils.log import DEFAULT_LOGGING

LOGGING = DEFAULT_LOGGING
LOGGING["handlers"]["mail_admins"]["include_html"] = True

# EMAIL
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "localhost"
EMAIL_PORT = 25
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = "WC Blue Pages<noreply@bluepages.ecostrust.org>"

# Registration
# https://django-registration.readthedocs.io/en/3.3/settings.html
REGISTRATION_OPEN = False

# Authentication
# https://docs.djangoproject.com/en/3.2/topics/auth/default/#auth-web-requests
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Los_Angeles"

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "sass_processor.finders.CssFinder",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
# STATIC_ROOT = '/usr/local/apps/wcbluepages/bluepages/static_root'
STATIC_ROOT = os.path.join(BASE_DIR, "static_root")

MEDIA_URL = "/media/"
# MEDIA_ROOT = '/usr/local/apps/wcbluepages/bluepages/media_root'
MEDIA_ROOT = os.path.join(BASE_DIR, "media_root")

# SASS settings
# https://github.com/jrief/django-sass-processor

SASS_PROCESSOR_INCLUDE_DIRS = [
    os.path.join(BASE_DIR, "static/app/scss"),
]

# Search for SASS files in other INSTALLED_APPS
# files matching regex pattern: ^_.+\.(scss|sass)$ are processed
# human pattern: _*.(scss|sass)
# A best practice is that SASS files which start with an underscore are meant to be
SASS_PROCESSOR_AUTO_INCLUDE = True

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

IMPORT_SRID = 3857

REQUIRE_ACCOUNT = True

SITE_ID = 1

try:
    from .local_settings import *
except Exception:
    print("Unable to import local_settings")
    pass
