# Generated by Django 5.2.11 on 2026-02-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=254)),
                ('line_2', models.CharField(blank=True, default=None, max_length=254)),
                ('city', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('zip_code', models.CharField(max_length=25, verbose_name='Zip/Postal Code')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['city', 'zip_code', 'line_1', 'line_2'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('postal_code', models.CharField(help_text="i.e. 'USA'", max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
