# Generated by Django 3.2.13 on 2022-06-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['city', 'zip_code', 'line_1', 'line_2'], 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name', 'state'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
