# Generated by Django 3.2.16 on 2022-12-15 19:59

from django.db import migrations, models

def migrate_address_field_obj_to_str(apps, schema_editor):
    Address = apps.get_model('address', 'Address')
    for address in Address.objects.all():
        address.city_str = str(address.city)
        address.state_str = str(address.city.state)
        address.country_str = str(address.city.state.country.postal_code)

def revert_migrate_address_field_obj_to_str(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20220608_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_str',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country_str',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state_str',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=25, verbose_name='Zip/Postal Code'),
        ),
        migrations.RunPython(migrate_address_field_obj_to_str, revert_migrate_address_field_obj_to_str)
    ]
