# Generated by Django 3.2.16 on 2022-12-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20221215_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='city_str',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='country_str',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state_str',
            new_name='state',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
