# Generated by Django 5.2.11 on 2026-02-11 18:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import phone_field.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Ms., Sir, Sra., etc...', max_length=254, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, default='', max_length=254, verbose_name='First/Given Name')),
                ('last_name', models.CharField(max_length=254, verbose_name='Last/Family Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=254, verbose_name='Middle Name(s)/Initial(s)')),
                ('post_title', models.CharField(blank=True, default='', help_text='Esq., III, Jr., etc...', max_length=254, verbose_name='Additional Titles')),
                ('pronouns', models.CharField(blank=True, default='', help_text='She/Her, They/Them, etc...', max_length=254, verbose_name='Pronouns')),
                ('job_title', models.CharField(blank=True, default='', max_length=254, verbose_name='Job Title/Position')),
                ('expertise', models.CharField(blank=True, default='', max_length=254, verbose_name='Area(s) of expertise')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True, verbose_name='Work/Desk phone no.')),
                ('mobile_phone', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True, verbose_name='Mobile phone no.')),
                ('office_phone', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True, verbose_name='Department/General phone no.')),
                ('fax', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True)),
                ('line_1', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('line_2', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Zip/Postal Code')),
                ('preferred_contact_method', models.CharField(blank=True, default='', help_text='i.e. email, phone, no preference, etc...', max_length=254, verbose_name='Preferred contact method(s)')),
                ('show_on_entity_page', models.BooleanField(blank=True, choices=[(None, 'Default'), (True, 'Public'), (False, 'Filtered')], default=None, help_text='<span>Public: Display contact on the entity page.</span><span>Filtered: Contact only disoverable via region/topic search.</span><span>Default: Do whatever the entity does.</span>', null=True, verbose_name='Contact Visibility')),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_test_data', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'middle_name', 'entity', 'job_title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name of Entity')),
                ('entity_type', models.CharField(blank=True, choices=[(None, 'Unspecified'), ('Tribal', 'Tribal'), ('Federal', 'Federal'), ('State', 'State')], default=None, max_length=15, null=True, verbose_name='Type of Entity')),
                ('website', models.URLField(blank=True, default=None)),
                ('line_1', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('line_2', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Zip/Postal Code')),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True)),
                ('fax', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True)),
                ('show_contacts', models.BooleanField(blank=True, choices=[(None, 'Default'), (True, 'Public'), (False, 'Filtered')], default=None, help_text='Public: Display all known contacts for this entity on the entity page.<br />Filtered: Contacts only disoverable via region/topic search.<br />Default: Do whatever the parent entity does.', null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entity')),
            ],
            options={
                'verbose_name_plural': 'Entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Ms., Sir, Sra., etc...', max_length=254, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, default='', max_length=254, verbose_name='First/Given Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=254, verbose_name='Middle Name(s)/Initial(s)')),
                ('post_title', models.CharField(blank=True, default='', help_text='Esq., III, Jr., etc...', max_length=254, verbose_name='Additional Titles')),
                ('pronouns', models.CharField(blank=True, default='', help_text='She/Her, They/Them, etc...', max_length=254, verbose_name='Pronouns')),
                ('job_title', models.CharField(blank=True, default='', max_length=254, verbose_name='Job Title/Position')),
                ('expertise', models.CharField(blank=True, default='', max_length=254, verbose_name='Area(s) of expertise')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True, verbose_name='Work/Desk phone no.')),
                ('mobile_phone', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True, verbose_name='Mobile phone no.')),
                ('office_phone', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True, verbose_name='Department/General phone no.')),
                ('fax', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True)),
                ('line_1', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('line_2', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('zip_code', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Zip/Postal Code')),
                ('preferred_contact_method', models.CharField(blank=True, default='', help_text='i.e. email, phone, no preference, etc...', max_length=254, verbose_name='Preferred contact method(s)')),
                ('show_on_entity_page', models.BooleanField(blank=True, choices=[(None, 'Default'), (True, 'Public'), (False, 'Filtered')], default=None, help_text='<span>Public: Display contact on the entity page.</span><span>Filtered: Contact only disoverable via region/topic search.</span><span>Default: Do whatever the entity does.</span>', null=True, verbose_name='Contact Visibility')),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('self_suggestion', models.BooleanField(default=False, help_text='this record is my own information about me', verbose_name='I am the contact')),
                ('last_name', models.CharField(blank=True, default='', max_length=254, verbose_name='Last/Family Name')),
                ('address_line_1', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('address_line_2', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('address_city', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('address_state', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='State/Province')),
                ('address_country', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('address_zip_code', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Zip/Postal Code')),
                ('other_entity_name', models.CharField(blank=True, default='', help_text='If contact belongs to an unlisted entity, name it here.', max_length=254, verbose_name='Other Entity Name')),
                ('sub_entity_name', models.CharField(blank=True, default='', help_text='If contact belongs to a specific division within their organization, please specify it here.', max_length=254, verbose_name='Division/Sub-entity')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', help_text='Has suggestion been approved or declined?', max_length=20, verbose_name='Suggestion status')),
                ('description', models.TextField(blank=True, default=None, help_text='If you are updating an existing contact, what specific changes are you trying to propose in this form?', null=True, verbose_name='Describe the change you are suggesting (if you are updating an existing contact)')),
                ('contact', models.ForeignKey(blank=True, default=None, help_text='If suggesting edits for an existing contact, identify them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.contact', verbose_name='Contact to edit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User proposing this change')),
                ('entity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entity', verbose_name='Entity/Organization')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'middle_name', 'entity', 'job_title', 'user__username'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entity', verbose_name='Entity/Organization'),
        ),
        migrations.CreateModel(
            name='RegionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('postal_code', models.CharField(help_text="i.e. 'WA'", max_length=4)),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.country')),
            ],
            options={
                'ordering': ['name', 'country'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Region ID')),
                ('name', models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name='Name of Region')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, default=None, null=True, srid=3857, verbose_name='Region Boundary')),
                ('depth_type', models.CharField(choices=[('N', 'Near Shore'), ('M', 'Mid Water'), ('O', 'Offshore')], default='N', max_length=1, verbose_name='Region Depth Type')),
                ('id_num', models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Region Number')),
                ('states', models.ManyToManyField(to='app.regionstate', verbose_name='States')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name of Topic')),
                ('notes', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_topic')],
            },
        ),
        migrations.CreateModel(
            name='RecordSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', help_text='Has suggestion been approved or declined?', max_length=20, verbose_name='Suggestion status')),
                ('contact_suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contactsuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User proposing this change')),
                ('regions', models.ManyToManyField(to='app.region')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topic')),
            ],
            options={
                'ordering': ['topic', 'contact_suggestion'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contact')),
                ('regions', models.ManyToManyField(to='app.region')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topic')),
            ],
            options={
                'ordering': ['topic', 'contact'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='contactsuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending'), models.Q(('contact', None), _negated=True)), fields=('user', 'contact', 'status'), name='unique_contact_suggestion'),
        ),
        migrations.AddConstraint(
            model_name='recordsuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('user', 'topic', 'contact_suggestion', 'status'), name='unique_record_suggestion'),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('topic', 'contact'), name='unique_record'),
        ),
    ]
