# Generated by Django 3.2.13 on 2022-06-01 21:20

import address.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Ms., Sir, Sra., etc...', max_length=254, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, max_length=254, verbose_name='First/Given Name')),
                ('last_name', models.CharField(max_length=254, verbose_name='Last/Family Name')),
                ('middle_name', models.CharField(blank=True, max_length=254, verbose_name='Middle Name(s)/Initial(s)')),
                ('post_title', models.CharField(blank=True, help_text='Esq., III, Jr., etc...', max_length=254, verbose_name='Additional Titles')),
                ('preferred_pronouns', models.CharField(blank=True, help_text='She/Her, They/Them, etc...', max_length=254, verbose_name='Preferred Pronouns')),
                ('job_title', models.CharField(blank=True, max_length=254, verbose_name='Job Title/Position')),
                ('expertise', models.CharField(blank=True, max_length=254, verbose_name='Expertise')),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True)),
                ('address', address.models.AddressField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'middle_name', 'entity', 'job_title'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name='Name of Region')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, default=None, null=True, srid=3857, verbose_name='Region Boundary')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name of Topic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contact')),
                ('regions', models.ManyToManyField(to='app.Region')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topic')),
            ],
            options={
                'ordering': ['topic', 'contact'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name of Entity')),
                ('website', models.URLField(blank=True, default=None)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True)),
                ('address', address.models.AddressField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entity'),
        ),
    ]
