# Generated by Django 5.2.11 on 2026-02-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='show_on_entity_page',
            field=models.BooleanField(blank=True, choices=[(None, 'Default'), (True, 'Public'), (False, 'Filtered')], default=None, help_text='<span>Public: Display contact on the entity page.</span><br /><span>Filtered: Contact only discoverable via region/topic search.</span><br /><span>Default: Do whatever the entity does.</span>', null=True, verbose_name='Contact Visibility'),
        ),
        migrations.AlterField(
            model_name='contactsuggestion',
            name='show_on_entity_page',
            field=models.BooleanField(blank=True, choices=[(None, 'Default'), (True, 'Public'), (False, 'Filtered')], default=None, help_text='<span>Public: Display contact on the entity page.</span><br /><span>Filtered: Contact only discoverable via region/topic search.</span><br /><span>Default: Do whatever the entity does.</span>', null=True, verbose_name='Contact Visibility'),
        ),
    ]
