# Generated by Django 3.2.13 on 2022-07-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20220608_2335'),
        ('app', '0002_auto_20220609_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='region',
            name='depth_type',
            field=models.CharField(choices=[('N', 'Near Shore'), ('M', 'Mid Water'), ('O', 'Offshore')], default='N', max_length=1, verbose_name='Region Depth Type'),
        ),
        migrations.AddField(
            model_name='region',
            name='id_num',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Region Number'),
        ),
        migrations.AddField(
            model_name='region',
            name='states',
            field=models.ManyToManyField(to='address.State', verbose_name='States'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Region ID'),
        ),
    ]
