# Generated by Django 5.2.13 on 2026-04-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsuggestion',
            name='self_suggestion',
        ),
    ]
