# Generated by Django 3.2.16 on 2022-12-14 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_auto_20220608_2335'),
        ('app', '0004_entity_entity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Ms., Sir, Sra., etc...', max_length=254, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, default='', max_length=254, verbose_name='First/Given Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=254, verbose_name='Middle Name(s)/Initial(s)')),
                ('post_title', models.CharField(blank=True, default='', help_text='Esq., III, Jr., etc...', max_length=254, verbose_name='Additional Titles')),
                ('preferred_pronouns', models.CharField(blank=True, default='', help_text='She/Her, They/Them, etc...', max_length=254, verbose_name='Preferred Pronouns')),
                ('job_title', models.CharField(blank=True, default='', max_length=254, verbose_name='Job Title/Position')),
                ('expertise', models.CharField(blank=True, default='', max_length=254, verbose_name='Expertise')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True)),
                ('fax', phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True)),
                ('preferred_contact_method', models.CharField(blank=True, default='', max_length=254, verbose_name='Preferred contact method(s)')),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=254, verbose_name='Last/Family Name')),
                ('other_entity_name', models.CharField(blank=True, default='', help_text='If contact belongs to an unlisted entity, name it here.', max_length=254, verbose_name='Other Entity Name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', help_text='Suggestion has yet to be approved or declined', max_length=20, verbose_name='Suggestion is open')),
                ('description', models.TextField(blank=True, default=None, help_text='If you are updating an existing contact, what specific changes are you trying to propose in this form?', null=True, verbose_name='Describe the proposed update')),
                ('address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('contact', models.ForeignKey(blank=True, default=None, help_text='If suggesting edits for an existing contact, identify them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.contact', verbose_name='Contact to edit')),
                ('entity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User proposing this change')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'middle_name', 'entity', 'job_title', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='RecordSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contactsuggestion')),
                ('regions', models.ManyToManyField(to='app.Region')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topic')),
            ],
            options={
                'ordering': ['topic', 'contact_suggestion'],
            },
        ),
    ]
