# Generated by Django 3.2.16 on 2022-12-15 18:59

from django.db import migrations, models
import django.db.models.deletion

def copy_state_to_region_state(apps, schema_editor):
    Address = apps.get_model('address', 'State')
    RegionState = apps.get_model('app', 'RegionState')
    for address in Address.objects.all():
        RegionState.objects.create(pk=address.pk, name=address.name, postal_code=address.postal_code, country=address.country)

def revert_copy_to_region_state(apps, schema_editor):
    RegionState = apps.get_model('app', 'RegionState')
    for state in RegionState.objects.all():
        state.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20220608_2335'),
        ('app', '0005_contactsuggestion_recordsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsuggestion',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', help_text='Has suggestion been approved or declined?', max_length=20, verbose_name='Suggestion status'),
        ),
        migrations.CreateModel(
            name='RegionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('postal_code', models.CharField(help_text="i.e. 'WA'", max_length=4)),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.country')),
            ],
            options={
                'ordering': ['name', 'country'],
            },
        ),
        migrations.RunPython(copy_state_to_region_state, revert_copy_to_region_state),
    ]
