# Generated by Django 3.2.16 on 2022-12-15 19:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20221215_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='states',
            field=models.ManyToManyField(to='app.RegionState', verbose_name='States'),
        ),
    ]
