# Generated by Django 3.2.16 on 2022-12-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_region_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsuggestion',
            name='address',
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='address_city',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='address_country',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='address_line_1',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='address_line_2',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='address_state',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='address_zip_code',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Zip/Postal Code'),
        ),
    ]
