# Generated by Django 3.2.16 on 2022-12-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20221215_1644'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contactsuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('contact', None), _negated=True), fields=('user', 'contact'), name='unique_contact_suggestion'),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('topic', 'contact'), name='unique_record'),
        ),
        migrations.AddConstraint(
            model_name='recordsuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('user', 'topic', 'contact_suggestion'), name='unique_record_suggestion'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_topic'),
        ),
    ]
