# Generated by Django 3.2.16 on 2023-01-09 22:21

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20221222_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile_phone',
            field=phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True, verbose_name='Mobile phone no.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='office_phone',
            field=phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True, verbose_name='Department/General phone no.'),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='mobile_phone',
            field=phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True, verbose_name='Mobile phone no.'),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='office_phone',
            field=phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True, verbose_name='Department/General phone no.'),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='self_suggestion',
            field=models.BooleanField(default=False, help_text='this record is my own information about me', verbose_name='I am the contact'),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='show_on_entity_page',
            field=models.BooleanField(blank=True, choices=[(None, 'Inherit'), (True, 'Public'), (False, 'Private')], default=None, help_text='Public: Display contact on the entity page.<br />Private: Contact only disoverable via region/topic search.<br />Inherit: Do whatever the entity does.', null=True),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='sub_entity_name',
            field=models.CharField(blank=True, default='', help_text='If contact belongs to a specific division within their organization, please specify it here.', max_length=254, verbose_name='Division/Sub-entity'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entity', verbose_name='Entity/Organization'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='expertise',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Area(s) of expertise'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True, verbose_name='Work/Desk phone no.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='preferred_contact_method',
            field=models.CharField(blank=True, default='', help_text='i.e. email, phone, no preference, etc...', max_length=254, verbose_name='Preferred contact method(s)'),
        ),
        migrations.AlterField(
            model_name='contactsuggestion',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.entity', verbose_name='Entity/Organization'),
        ),
        migrations.AlterField(
            model_name='contactsuggestion',
            name='expertise',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Area(s) of expertise'),
        ),
        migrations.AlterField(
            model_name='contactsuggestion',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default=None, max_length=31, null=True, verbose_name='Work/Desk phone no.'),
        ),
        migrations.AlterField(
            model_name='contactsuggestion',
            name='preferred_contact_method',
            field=models.CharField(blank=True, default='', help_text='i.e. email, phone, no preference, etc...', max_length=254, verbose_name='Preferred contact method(s)'),
        ),
    ]
