# Generated by Django 3.2.16 on 2023-01-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20221215_1207'),
        ('app', '0011_auto_20230109_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsuggestion',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
