# Generated by Django 3.2.16 on 2023-01-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contactsuggestion_address'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contactsuggestion',
            name='unique_contact_suggestion',
        ),
        migrations.RemoveConstraint(
            model_name='recordsuggestion',
            name='unique_record_suggestion',
        ),
        migrations.AddConstraint(
            model_name='contactsuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending'), models.Q(('contact', None), _negated=True)), fields=('user', 'contact', 'status'), name='unique_contact_suggestion'),
        ),
        migrations.AddConstraint(
            model_name='recordsuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('user', 'topic', 'contact_suggestion', 'status'), name='unique_record_suggestion'),
        ),
    ]
