# Generated by Django 3.2.16 on 2023-01-31 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20230112_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='show_on_entity_page',
            field=models.BooleanField(blank=True, choices=[(None, 'Default'), (True, 'Public'), (False, 'Filtered')], default=None, help_text='Public: Display contact on the entity page.<br />Filtered: Contact only disoverable via region/topic search.<br />Default: Do whatever the entity does.', null=True, verbose_name='Contact Visibility'),
        ),
        migrations.AlterField(
            model_name='contactsuggestion',
            name='show_on_entity_page',
            field=models.BooleanField(blank=True, choices=[(None, 'Default'), (True, 'Public'), (False, 'Filtered')], default=None, help_text='Public: Display contact on the entity page.<br />Filtered: Contact only disoverable via region/topic search.<br />Default: Do whatever the entity does.', null=True, verbose_name='Contact Visibility'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='show_contacts',
            field=models.BooleanField(blank=True, choices=[(None, 'Default'), (True, 'Public'), (False, 'Filtered')], default=None, help_text='Public: Display all known contacts for this entity on the entity page.<br />Filtered: Contacts only disoverable via region/topic search.<br />Default: Do whatever the parent entity does.', null=True),
        ),
    ]
