# Generated by Django 3.2.16 on 2023-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20230131_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pronouns',
            field=models.CharField(blank=True, default='', help_text='She/Her, They/Them, etc...', max_length=254, verbose_name='Pronouns'),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='pronouns',
            field=models.CharField(blank=True, default='', help_text='She/Her, They/Them, etc...', max_length=254, verbose_name='Pronouns'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='show_on_entity_page',
            field=models.BooleanField(blank=True, choices=[(None, 'Default'), (True, 'Public'), (False, 'Filtered')], default=None, help_text='<span>Public: Display contact on the entity page.</span><span>Filtered: Contact only disoverable via region/topic search.</span><span>Default: Do whatever the entity does.</span>', null=True, verbose_name='Contact Visibility'),
        ),
        migrations.AlterField(
            model_name='contactsuggestion',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='If you are updating an existing contact, what specific changes are you trying to propose in this form?', null=True, verbose_name='Describe the change you are suggesting (if you are updating an existing contact)'),
        ),
        migrations.AlterField(
            model_name='contactsuggestion',
            name='show_on_entity_page',
            field=models.BooleanField(blank=True, choices=[(None, 'Default'), (True, 'Public'), (False, 'Filtered')], default=None, help_text='<span>Public: Display contact on the entity page.</span><span>Filtered: Contact only disoverable via region/topic search.</span><span>Default: Do whatever the entity does.</span>', null=True, verbose_name='Contact Visibility'),
        ),
    ]
