# Generated by Django 3.2.16 on 2023-04-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    def pronouns_are_pronouns(apps, schema_editor):
        Contact = apps.get_model('app', 'Contact')
        for contact in Contact.objects.all():
            contact.pronouns = contact.preferred_pronouns
            contact.save()
        ContactSuggestion = apps.get_model('app', 'ContactSuggestion')
        for suggestion in ContactSuggestion.objects.all():
            suggestion.pronouns = suggestion.preferred_pronouns
            suggestion.save()


    dependencies = [
        ('app', '0015_auto_20230406_0838'),
    ]

    operations = [
        migrations.RunPython(pronouns_are_pronouns)
    ]
