# Generated by Django 3.2.16 on 2023-04-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20230406_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='preferred_pronouns',
        ),
        migrations.RemoveField(
            model_name='contactsuggestion',
            name='preferred_pronouns',
        ),
    ]
