# Generated by Django 3.2.16 on 2023-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20230406_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='line_1',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='line_2',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='contact',
            name='zip_code',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Zip/Postal Code'),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='line_1',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='line_2',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='contactsuggestion',
            name='zip_code',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Zip/Postal Code'),
        ),
        migrations.AddField(
            model_name='entity',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='line_1',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='line_2',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='entity',
            name='zip_code',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Zip/Postal Code'),
        ),
    ]
