# Generated by Django 3.2.16 on 2023-04-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    def flatten_addresses(apps, schema_editor):
        Entity = apps.get_model('app', 'Entity')
        for entity in Entity.objects.exclude(address=None):
            entity.line_1 = entity.address.line_1
            entity.line_2 = entity.address.line_2
            entity.city = entity.address.city
            entity.state = entity.address.state
            entity.country = entity.address.country
            entity.zip_code = entity.address.zip_code
            entity.save()
        Contact = apps.get_model('app', 'Contact')
        for contact in Contact.objects.exclude(address=None):
            contact.line_1 = contact.address.line_1
            contact.line_2 = contact.address.line_2
            contact.city = contact.address.city
            contact.state = contact.address.state
            contact.country = contact.address.country
            contact.zip_code = contact.address.zip_code
            contact.save()
        ContactSuggestion = apps.get_model('app', 'ContactSuggestion')
        for suggestion in ContactSuggestion.objects.all():
            suggestion.line_1 = suggestion.address_line_1
            suggestion.line_2 = suggestion.address_line_2
            suggestion.city = suggestion.address_city
            suggestion.state = suggestion.address_state
            suggestion.country = suggestion.address_country
            suggestion.zip_code = suggestion.address_zip_code
            suggestion.save()

    dependencies = [
        ('app', '0018_auto_20230406_1151'),
    ]

    operations = [
        migrations.RunPython(flatten_addresses)
    ]
